output "network_id" {
  value       = kaleido_platform_network.this.id
  description = "ID of the BesuNetwork. Pass to the chaininfra-besu-node module's `network_id`."
}

output "stack_id" {
  value       = kaleido_platform_stack.this.id
  description = "ID of the chain-infrastructure stack wrapping the network. Pass to the chaininfra-besu-node module's `stack_id`."
}

output "network_name" {
  value       = kaleido_platform_network.this.name
  description = "Display name of the BesuNetwork."
}

output "chain_id" {
  value       = try(kaleido_platform_network.this.info["chainID"], null)
  description = "Chain ID captured from the network after creation (generated by the platform in automated init mode when `chain_id` was not set)."
}

output "network_info" {
  value       = kaleido_platform_network.this.info
  description = "Top-level config captured from the network after creation, including generated values such as the chain ID."
}
